AppBundle\Entity\Criteria:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CriteriaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        iconpath:
            type: string
            length: '45'
            unique: true
    lifecycleCallbacks: {  }
