
create_user:
    path:     /createUser
    defaults: { _controller: AppBundle:UserController:createUser }

get_liste_users:
    path:     /getListeUsers
    defaults: { _controller: AppBundle:UserController:getListeUsers }
